### PR TITLE
Added support for course pages.

### PR DESCRIPTION
**Pull request by Nexite**
Adds support for all /course pages, also fixed some formatting in manifest.json

### CODE REVIEW

**Comment by Orion31Dev** [comment]
I really like this idea, but it seems silly to make a whole new file that only differs from async-home.js in one line. Also, I wouldn't want you to have wasted effort because I just rewrote most of the code in #6 and when we merge dev with master, async-course will still have the old code that was changed. 

Instead (and I'm looking at the dev branch here) all of this from home.js:
```javascript
const updateAssignmentElements = function (completedAssignments, assignmentElements) {
  let completedAssignmentElements = [];

  // Get completed assignment elements
  $.each(assignmentElements, (index, element) => {
    if (!element.pathname.includes('assignment')) return;

    let assignmentID = element.pathname.split('/')[2];
    $.each(completedAssignments, (index, obj) => {
      if (assignmentID === obj.id)
        completedAssignmentElements.push({
          element: element,
          description: obj.description,
        });
    });
  });

  // Update each completed assignment
  $.each(completedAssignmentElements, (index, val) => {
    const element = val.element;

    const time = $($(element).parent().find('span.upcoming-time')[0]);
    const span = $(document.createElement('span'));

    span.addClass('check');

    span.html('✔');
    span.css('color', 'var(--completed-color)');

    // Make sure assignment has a due date
    if (typeof time !== 'undefined') {
      time.html(time.html() + ' | ' + val.description);
      time.css('color', 'var(--completed-color)');
    }

    element.parentNode.insertBefore(span[0], element.nextSibling);
  });
};
```
can be moved to utils.js and renamed to something like `updateAssignmentsFromArray`. Then in course.js you could just have the few lines that need changing
```javascript
let assignmentElements;

$(document).ready(() => {
  assignmentElements = $('div.upcoming-event.course-event span a'); // update this to the write selector in course.js
  get(assignments).then(updateAssignmentElements);
});

// Add this to home.js and course.js
const updateAssignmentElements = function (completedAssignments) {
  updateAssignmentsFromArray(completedAssignments, assignmentElements);
}
```
Obviously that was a stupid implementation, but that way you don't have to reuse so many lines of code.

**Comment by Nexite** [comment]
yeah I was thinking about doing that, I'm new to jquery and wasn't too sure how it worked, I understand it more now and will try to do this.

**Comment by Nexite** [comment]
I redid this for the dev branch, I also made it so it formats the upcoming events to work with the update function. should I close this pr and make a new pr for dev?

**Comment by Orion31Dev** [comment]
You can update this one but make sure you are merging with `dev` from your forked `dev`. Also make sure to `git pull` from dev first.

**Comment by Orion31Dev** [comment]
@Nexite you still are trying to merge from your `master` branch so make sure to update it to `dev`. Idk if you can do that, if you can't just make a new PR.

**Pull request merged**
